name: CI

on:


  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:


  build:
  
  
    runs-on: ubuntu-latest


    steps:
    
    
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v1
        
        
        with:
        
        
          python-version: 3.9
          architecture: x64
          cache: 'pip'
          
          
      - name: Copiar Configurações .env
        run: |
          cp contrib/env-sample .env
          
          
      - name: Instalar dependências
        run: |
          pip install -r requirements-dev.txt
          
          
      - name: Rodar flake8
        run: |
          pipenv run flake8 .
        uses: py-actions/flake8@v1
        with:
          checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
          
          
      - name: Rodar Testes Automáticos
        run: |
          pytest --cov=pypro

