name: Python application

on:
  push:
    branches:
      - master
      - 18
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt codecov

      - name: Test with pytest
        run: pytest libpythonpro --cov=libpythonpro

      - name: Rodar Flake8
        run: flake8

      - name: Relatório Coverage
        env:
          CODECOV_TOKEN: '267b8dc4-9196-4e0b-a809-bdb8d224f6c1'
        run:
          codecov

